export const CURRENT_LOCATION_WEATHER = 'CURRENT_LOCATION_WEATHER';
export const CITY_FORECAST = 'CITY_FORECAST';
export const HOURLY_FORECAST = 'HOURLY_FORECAST';
export const SUCCESS_HOURLY_FORECAST = 'SUCCESS_HOURLY_FORECAST';
export const SUCCESS_FORECAST = 'SUCCESS_FORECAST';
export const SUCCESS_CITY_FORECAST = 'SUCCESS_CITY_FORECAST';
export const GET_CITIES = 'GET_CITIES';
export const SUCCESS_CITIES = 'SUCCESS_CITIES';